theme: jekyll-theme-minimal
title: Alex LaValley
description: I make things, and then I write code to tell it what to do.  
Computer Engineering • Sustainability Studies  
University of Minnesota - Fall 2020   
